#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-2 -d 1 2 3 4 5 6 7
# bspc monitor DVI-D-0 -d 8 9 0

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 80
bspc config bottom_padding 80
bspc config left_padding 90
bspc config right_padding 90

bspc config focused_border_color "#89DCEB"

$HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/Wallpapers/Fedora-Catppuccin-4k.png &
xsetroot -cursor_name left_ptr &
dunst &
conky -c $HOME/.config/conky/catppuccin.conf &
picom --experimental-backends &
export QT_QPA_PLATFORMTHEME="qt5ct"
